-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyUFNhZjet/AOUZQ2
ga/GoaAfZ87qwqEyA8L7b7SHIDWgCgYIKoZIzj0DAQehRANCAATDrnHdl3ANdkq9
0M2GXqlOFbliq0beYgIO07+Upl4FUm6X3/tlJb9jwk+MLikPvg8cm8p9vqJ+exxM
OyLBOrqo
-----END PRIVATE KEY-----